version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0